CREATE TABLE Triangle(X INT PRIMARY KEY,Y INT NOT NULL,Z INT NOT NULL);
INSERT INTO Triangle VALUES(13,15,30),(10,20,15);
SELECT *,CASE WHEN X+Y>Z AND Y+Z>X AND Z+X>Y THEN "YES" ELSE "NO" END AS triangle  FROM Triangle ;